# Build and deploy the site
name: Publish app
on:
  workflow_dispatch:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Move static assets
        run: npm run publish
      - name: Generate the index file
        run: npm run svg && node ./src/functions/ssr.js
      - name: Generate bundled files
	      run: npm run build