# Build and deploy the site
name: Publish app
on:
  workflow_dispatch:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - run: mkdir -p public
      - name: Generate bundled files
        run: npm run build
      - name: Move static assets
        run: npm run static
      - name: Generate the index file
        run: |
          npm run svg
          node ./src/functions/ssr.js
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
